version = 1

[[analyzers]]
name = "php"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Priyank-cyber/spinnaker"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"